### PR TITLE
Fixes Center Chess Board #1

### PR DESCRIPTION
**Pull request by int32at**

### CODE REVIEW

**Comment by nikhilkulkarni1755** [comment]
Thanks for the edit! However, with width 50% the board is lopsided

Chess Board centered but lopsided

for me, width: 50% works out

Chess Board centered

try this out and send me screenshots. if you are getting the same results then update the req with new code thanks

**Comment by nikhilkulkarni1755** [comment]
* 50% width doesn't work, looks lopsided

**Comment by int32at** [comment]
looks fine for me? 
Screenshot 2023-11-28 at 21 30 11

**Comment by nikhilkulkarni1755** [comment]
Hi found the issue. When using an external monitor, it shows the gaps. 

https://github.com/nikhilkulkarni1755/Chess/assets/28766327/5be71fb6-7ca6-43b0-98fd-b00b2ab9c876

Similarly, when adjusting the screen width for mobile, the resize is off

https://github.com/nikhilkulkarni1755/Chess/assets/28766327/4c008bcc-e2fe-41c0-aa44-bd5fdd6cf019

**Pull request merged**
